"""
Default configuration of the bot

DO NOT EDIT THIS FILE to configure your instance of the bot, instead edit `/settings.py`.
"""

# ----------------------------------------------------------------------------------------------------------------------
# Internationalisation
#
# Language to fall back to if there is no translation to the user's language. Default is "en".
DEFAULT_LANGUAGE = "en"
# Supported languages.  Must be a subset of languages that present in the `locales` directory.  Default is a tuple that
# contains all available languages.
SUPPORTED_LANGUAGES = ("en", "ru")
