%YAML 1.2
---
# Configuration for the audax-tracker Telegram bot

# ----------------------------------------------------------------------------------------------------------------------
# Mandatory settings
#
# Token of the bot, obtained from BotFather
BOT_TOKEN: "{bot_token}"
# ID of the chat with the developer
DEVELOPER_CHAT_ID: 0
# URL of the remote endpoint that the data is fetched from
REMOTE_ENDPOINT_URL: "{remote_endpoint_url}"
# Authentication token used in requests to the remote endpoint
REMOTE_ENDPOINT_AUTH_TOKEN: "{remote_endpoint_token}"

# ----------------------------------------------------------------------------------------------------------------------
# Internationalisation
#
# Language to fall back to if there is no translation to the user's language. Default is "en".
# DEFAULT_LANGUAGE: "en"
# List of supported languages.  Must be a subset of languages that present in the `locales` directory.  Default is all
# available languages.
# SUPPORTED_LANGUAGES:
# - en
# - ru
# Time zone in which the event is held, and in which all dates and times are presented.  Default is "UTC".
# TIME_ZONE: "UTC"

# ----------------------------------------------------------------------------------------------------------------------
# Data fetching
#
# Fetching interval in minutes.  Default is 5.
# FETCHING_INTERVAL_MINUTES: 5

# ----------------------------------------------------------------------------------------------------------------------
# Event information
#
# URL of the page where the list of participants is published.  Default is empty.
# EVENT_PARTICIPANT_LIST_URL: ""
